apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: joinrpg-portal
  name: joinrpg-portal
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joinrpg-portal
  strategy: {}
  template:
    metadata:
      labels:
        app: joinrpg-portal
    spec:
      containers:
      - image:  joinrpg.azurecr.io/joinrpg.portal-dev
        name: server
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Development'
          - name: 'ConnectionStrings__DefaultConnection'
            valueFrom:
                secretKeyRef:
                  name: joinrpg-secrets
                  key: ConnectionStrings__DefaultConnection
        resources: {}
