
trigger:
  batch: true
  branches:
    include:
      - 'containers/main'
      
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')] 

  ${{ if eq(variables.isMaster, true) }}:
    imageSuffix: '' 

  ${{ if ne(variables.isMaster, true) }}:
    imageSuffix: '-dev' 

  azureSubscription: 'JoinRPG-subscription-connection'
  registryServiceConnection: 'JoinRPGacr'
  imageRepository: 'joinrpg.portal$(imageSuffix)'
  containerRegistry: 'joinrpg.azurecr.io'  
  dockerfilePath: 'src/JoinRpg.Portal/Dockerfile'
  rgName: 'joinrpg-k8s'
  verTag: '1.0.$(Build.BuildId)'
  imageFullName: '$(containerRegistry)/$(imageRepository):$(verTag)'

  keyVaultName: "joinrpg-k8s-kv"

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(registryServiceConnection)
        buildContext: .        
        tags: |
          latest
          $(verTag)

    - publish: $(System.DefaultWorkingDirectory)/Deployment
      artifact: DeployScripts
      
- stage: Deploy_Dev_Stage
  displayName: Deploy Dev/Stage
  dependsOn: Build
  jobs:
  - deployment: 'Deploy_Dev'
    displayName: Deploy app to the 'Dev' namespace'
    condition: ne(variables.isMaster, true)
    environment: Recova19_Dev
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:          
          steps:
          - task: AzureKeyVault@1
            inputs:
              azureSubscription: $(azureSubscription)
              keyVaultName: $(keyVaultName)
              secretsFilter: '*'
              runAsPreJob: false 

          - task: AzurePowerShell@4
            inputs:
              azureSubscription: $(azureSubscription)
              ScriptType: FilePath
              ScriptPath:  $(Pipeline.Workspace)/DeployScripts/test-env.ps1
              azurePowerShellVersion: LatestVersion