
trigger:
  batch: true
  branches:
    include:
      - 'containers/main'
      
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')] 

  ${{ if eq(variables.isMaster, true) }}:
    imageSuffix: '' 

  ${{ if ne(variables.isMaster, true) }}:
    imageSuffix: '-dev' 

  rgName: 'joinrpg-k8s'
  dockerfilePath: 'src/JoinRpg.Portal/Dockerfile'

  azureSubscription: 'JoinRPG-subscription-connection'
  registryServiceConnection: 'JoinRPG-ACR-connection'
  imageRepository: 'joinrpg.portal$(imageSuffix)'
  containerRegistry: 'joinrpg.azurecr.io'   
  verTag: '1.0.$(Build.BuildId)'
  imageFullName: '$(containerRegistry)/$(imageRepository):$(verTag)'

  keyVaultName: "joinrpg-k8s-kv"

  secretsName: "joinrpg-secrets"

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: gitversion/setup@0
      displayName: Install GitVersion
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: Determine Version
      inputs:
        useConfigFile: true
        configFilePath: 'GitVersion.yml'

    #- pwsh: |
    #    $fullSemVer = "$(GitVersion.FullSemVer)"
    #   if( $fullSemVer.Contains('+') ) {
    #     $tags = $fullSemVer.Replace("+","-"),"latest"
    #    }else{
    #      $tags = "$(GitVersion.Major)","$(GitVersion.Major).$(GitVersion.Minor)",$fullSemVer,"latest"
    #   }
    #    $tagListStr = $tags -join " "
    #    Write-Host "=== Tags list ==="
    #    $tagListStr
    #    Write-Host "##vso[task.setvariable variable=tagsList;]$tagListStr"
    #  displayName: Generate Tags

    - task: Docker@2
      displayName: Build and push an image (Prod)
      condition: not(contains(variables['GitVersion.FullSemVer'], '+'))
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(registryServiceConnection)
        buildContext: .
        tags: |
          latest
          $(GitVersion.Major)
          "$(GitVersion.Major).$(GitVersion.Minor)"
          $(GitVersion.FullSemVer)

    - task: Docker@2
      displayName: Build and push an image (Stage)
      condition: contains(variables['GitVersion.FullSemVer'], '+')
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(registryServiceConnection)
        buildContext: .
        tags: |
          $[ replace(variables['GitVersion.FullSemVer'], '+', '-') ]


    - publish: $(System.DefaultWorkingDirectory)/Deployment
      artifact: DeployScripts
      
- stage: Deploy_Dev_Stage
  variables:
    namespaceName: "dev"
  displayName: Deploy Dev/Stage
  dependsOn: Build
  jobs:
  - deployment: 'Deploy_Dev'
    displayName: Deploy app to the 'Dev' namespace'
    condition: eq(variables.isMaster, true)
    environment: Join-k8s-dev
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:          
          steps:
          - task: AzurePowerShell@4
            inputs:
              azureSubscription: $(azureSubscription)
              azurePowerShellVersion: LatestVersion
              ScriptType: FilePath
              ScriptPath: $(Pipeline.Workspace)/DeployScripts/Portal/Get-JoinSecrets.ps1
              scriptArguments:
                -VaultName '$(keyVaultName)' `
                -Prefix 'dev-' `
                -Namespace '$(namespaceName)' `
                -SecretName '$(secretsName) ' `
                -Path "$(Pipeline.Workspace)/DeployScripts/Portal/resources-dev/join-secrets.yaml"

          - task: KubernetesManifest@0
            displayName: "Delete old secrets"
            continueOnError: true
            inputs:
              action: delete
              arguments: secret $(secretsName) 
              kubernetesServiceConnection: JoinRPG-k8s-dev-connection
              namespace: $(namespaceName)

          - task: KubernetesManifest@0
            displayName: Deploy
            inputs:
              kubernetesServiceConnection: JoinRPG-k8s-dev-connection
              containers: |
                $(imageFullName)
              namespace: $(namespaceName)
              manifests: "$(Pipeline.Workspace)/DeployScripts/Portal/resources-dev/*.yaml"

