
trigger:
  batch: true
  branches:
    include:
      - 'containers/main'
      
variables:
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')] 

  ${{ if eq(variables.isMaster, true) }}:
    imageSuffix: '' 

  ${{ if ne(variables.isMaster, true) }}:
    imageSuffix: '-dev' 

  azureSubscription: 'JoinRPG-subscription-connection'
  registryServiceConnection: 'JoinRPG-ACR-connection'
  imageRepository: 'joinrpg.portal$(imageSuffix)'
  containerRegistry: 'joinrpg.azurecr.io'  
  dockerfilePath: 'src/JoinRpg.Portal/Dockerfile'
  rgName: 'joinrpg-k8s'
  verTag: '1.0.$(Build.BuildId)'
  imageFullName: '$(containerRegistry)/$(imageRepository):$(verTag)'

  keyVaultName: "joinrpg-k8s-kv"

  secretsName: "joinrpg-secrets"

  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - publish: $(System.DefaultWorkingDirectory)/Deployment
      artifact: DeployScripts
      
- stage: Deploy_Dev_Stage
  variables:
    namespaceName: "dev"
  displayName: Deploy Dev/Stage
  dependsOn: Build
  jobs:
  - deployment: 'Deploy_Dev'
    displayName: Deploy app to the 'Dev' namespace'
    condition: ne(variables.isMaster, true)
    environment: Join-k8s-dev
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:          
          steps:
          - task: AzureKeyVault@1
            inputs:
              azureSubscription: $(azureSubscription)
              keyVaultName: $(keyVaultName)
              secretsFilter: '*'
              runAsPreJob: false 

          - task: KubernetesManifest@0
            displayName: Create secret
            inputs: 
              action: createSecret
              secretType: generic
              kubernetesServiceConnection: JoinRPG-k8s-dev-connection
              secretArguments: --from-literal=ConnectionStrings__DefaultConnection=$(ConnectionString) --from-literal=Test_Var=TestValue
              secretName: $(secretsName)
              namespace: $(namespaceName)
