parameters:
- name: ingressHostName
  displayName: 'Ingress rule hostname'
  type: string
  default: ''

- name: keyVaultPrefix
  displayName: 'KeyVault secrets prefix'
  type: string
  default: ''

- name: releaseName
  displayName: 'Helm release name'
  type: string
  default: 'joinrpg-portal'

- name: namespace
  displayName: 'K8s namespace '
  type: string
  default: 'default'

- name: environment
  displayName: 'DevOps Environment'
  type: string
  default: 'default'

- name: name
  displayName: 'Deployment job name'
  type: string
  default: 'Deploy'

- name: displayName
  displayName: 'Deployment job name'
  type: string
  default: 'Deployment'

jobs:
- deployment: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  environment: ${{ parameters.environment }}
  pool:
    vmImage: $(vmImageName)
  strategy:
    runOnce:
      deploy:          
        steps:
        ##===========================
        ## Install tools
        ##===========================
        - task: HelmInstaller@1
          displayName: Install Helm
          inputs: 
            helmVersionToInstall: latest

        ##==========================================================================
        ## Get secrets from KeyVault and prepare parameters for Helm chart deploy 
        ##==========================================================================
        - task: AzurePowerShell@4
          inputs:
            azureSubscription: $(azureSubscription)
            azurePowerShellVersion: LatestVersion
            ScriptType: FilePath
            ScriptPath: $(Pipeline.Workspace)/DeployScripts/Portal/Prepare-ChartValues.ps1
            scriptArguments:
              -VaultName '$(keyVaultName)'
              -Prefix '${{ parameters.keyVaultPrefix }}'
              -Path '$(Pipeline.Workspace)/DeployScripts/Portal/deploy-values.yaml'
              -IngressHost '${{ parameters.ingressHostName }}'

        ##==========================================================================
        ## Deploy Helm chart  
        ##==========================================================================
        - task: HelmDeploy@0
          displayName: Install/Upgdare application (Helm)
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: $(azureSubscription)
            azureResourceGroup: $(rgName)
            kubernetesCluster: $(aksName)
            useClusterAdmin: true
            namespace: '${{ parameters.namespace }}'
            command: upgrade
            chartType: filepath
            chartPath: "$(Pipeline.Workspace)/Charts/joinrpg-portal"
            valueFile: "$(Pipeline.Workspace)/DeployScripts/Portal/deploy-values.yaml"
            releaseName: '${{ parameters.releaseName }}'
            install: true
            force: true
            waitForExecution: true