apiVersion: apps/v1
kind: Deployment
{{- $fullName := include "portal.fullname" . }}
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "portal.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "portal.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portal.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: {{ .Values.Environment }} 
          {{- range $key, $value := .Values.secrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: {{ $key }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      
      
